<?php

namespace Zikarsky\Bundle\QRCodeBundle\Storage;

use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Zikarsky\Bundle\QRCodeBundle\QRCodeInterface;
use Rhumsaa\Uuid\Uuid;

class SessionStorage implements StorageInterface
{
    /**
     * @var SessionInterface
     */
    protected $session;

    /**
     * @var string
     */
    protected $sessionKey;

    /**
     * @var QRCodeInterface[]
     */
    protected $qrCodes = [];

    public function __construct(SessionInterface $session, $sessionKey)
    {
        $this->session = $session;
        $this->sessionKey = $sessionKey;
        $this->qrCodes = $session->get($sessionKey, []);
    }

    /**
     * Store an QRCode
     *
     * An optional id can be passed, if ommitted an id is autogenerated
     *
     * @param QRCodeInterface $qrCode
     * @param string $id
     * @return string $id
     */
    public function store(QRCodeInterface $qrCode, $id = null)
    {
        $id =  $id ?: Uuid::uuid4();
        $this->qrCodes[$id] = $qrCode;

        // store in session
        $this->session->set($this->sessionKey, $this->qrCodes);

        return $id;
    }

    /**
     * Loads an QRCode from storage
     *
     * Returns null if there no QRCode stored for the given id
     *
     * @param string $id
     * @return QRCodeInterface|null
     */
    public function load($id)
    {
        return isset($this->qrCodes[$id]) ? $this->qrCodes[$id] : null;
    }
}
