<?php
namespace Zikarsky\Bundle\QRCodeBundle\Storage;


use Zikarsky\Bundle\QRCodeBundle\QRCodeInterface;

interface StorageInterface
{

    /**
     * Store an QRCode
     *
     * An optional id can be passed, if ommitted an id is autogenerated
     *
     * @param QRCodeInterface $qrCode
     * @param string $id
     * @return string $id
     */
    public function store(QRCodeInterface $qrCode, $id = null);

    /**
     * Loads an QRCode from storage
     *
     * @param string $id
     * @return QRCodeInterface
     */
    public function load($id);
}
